// <auto-generated />
using AG.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Genetic_algorithm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AG.Models.OptimizationParameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("ElitePercentage")
                        .HasColumnType("double");

                    b.Property<double>("MutationFrequency")
                        .HasColumnType("double");

                    b.Property<int>("NumberOfParents")
                        .HasColumnType("int");

                    b.Property<int>("OptimizationType")
                        .HasColumnType("int");

                    b.Property<int>("PopulationSize")
                        .HasColumnType("int");

                    b.Property<double>("PreferenceWeight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("OptimizationParameters");
                });
#pragma warning restore 612, 618
        }
    }
}
